// Code generated by fc-uniapp-x. DO NOT EDIT.
// 20261001

import { createPinia } from 'pinia'
import { createPersistPlugin } from './persist'

class FCStore {
	private piniaInstance : ReturnType<typeof createPinia>

	constructor() {
		this.piniaInstance = createPinia()
		this.piniaInstance.use(createPersistPlugin())
	}

	install(app : VueApp) : void {
		app.use(this.piniaInstance)
	}
}

export const Store = new FCStore()
