// Code generated by fc-uniapp-x. DO NOT EDIT.
// 20261001

import { defineStore } from 'pinia'

export const useFcSystemStore = defineStore('fcSystem', () => {
	const language = ref('auto')	//多语言设置，默认跟随系统
	const theme = ref('auto')		//主题设置，默认跟随系统

	return {
		language,
		theme,
	}
}, {
	persist: {
		key: 'fc-system'
	}
})
