// Code generated by fc-uniapp-x. DO NOT EDIT.
// 20261001

// 主题模式，auto=跟随系统，light=明亮模式，dark=暗黑模式
export type FCTypeThemeSetting = 'auto' | 'light' | 'dark'

//网络流式控制器。可中断、可重订阅，由 FC.Stream.stream() 返回。
export interface FCStreamController {
    task : RequestTask | null
    abort : () => void
}

// 网络请求 request 方法的第二个参数。true 表示带默认 Loading；传对象可配置 loadingText / onTask。
export interface FCRequestOptions {
    showLoading ?: boolean
    loadingText ?: string
    onTask ?: (task : RequestTask) => void
}

// FC.Request 构造函数的配置项。统一在 types.ts 暴露，业务侧可直接 import 使用。
export interface FCRequestConfig {
    baseURL ?: string
    timeout ?: number
    loadingText ?: string
    requestInterceptors ?: (config : RequestOptions<any>) => RequestOptions<any> | void | Promise<RequestOptions<any> | void>
    responseSuccess ?: (response : RequestSuccess<any>) => boolean
    responseComplete ?: () => void
    responseError ?: (error : any) => void
    responseParser ?: (data : any) => any
    shouldRefreshToken ?: (response : RequestSuccess<any>) => boolean
    refreshTokenMethod ?: () => Promise<boolean>
}

// upload 方法的第二个参数。形态与 FCRequestOptions 对齐，onTask 接收 UploadTask。
export interface FCUploadOptions {
    showLoading ?: boolean
    loadingText ?: string
    onTask ?: (task : UploadTask) => void
}

// FC.Upload 构造函数的配置项。统一在 types.ts 暴露，业务侧可直接 import 使用。
export interface FCUploadConfig {
    baseURL ?: string
    timeout ?: number
    loadingText ?: string
    uploadInterceptors ?: (config : UploadFileOptions) => UploadFileOptions | void | Promise<UploadFileOptions | void>
    uploadSuccess ?: (response : UploadFileSuccess) => boolean
    uploadComplete ?: () => void
    uploadError ?: (response : UploadFileSuccess | UploadFileFail) => void
    uploadParser ?: (data : string) => any
    shouldRefreshToken ?: (response : UploadFileSuccess) => boolean
    refreshTokenMethod ?: () => Promise<boolean>
}

// download 方法的第二个参数。形态与 FCRequestOptions 对齐，onTask 接收 DownloadTask。
export interface FCDownloadOptions {
    showLoading ?: boolean
    loadingText ?: string
    onTask ?: (task : DownloadTask) => void
}

// FC.Download 构造函数的配置项。统一在 types.ts 暴露，业务侧可直接 import 使用。
export interface FCDownloadConfig {
    baseURL ?: string
    timeout ?: number
    loadingText ?: string
    downloadInterceptors ?: (config : DownloadFileOptions) => DownloadFileOptions | void | Promise<DownloadFileOptions | void>
    downloadSuccess ?: (response : DownloadFileSuccess) => boolean
    downloadComplete ?: () => void
    downloadError ?: (response : DownloadFileSuccess | DownloadFileFail) => void
    downloadParser ?: (response : DownloadFileSuccess) => any
    shouldRefreshToken ?: (response : DownloadFileSuccess) => boolean
    refreshTokenMethod ?: () => Promise<boolean>
}

// 路由配置。
export type FCTypeRouterConfig = {
    shouldInterceptRoute ?: () => boolean
    interceptFunc ?: () => void
}

// 路由跳转方法的参数。
export type FCTypeRouteParams = Record<string, string | number | boolean | null | object>

/* ------------------------------------------------------------------ */
/* WebSocket                                                           */
/* ------------------------------------------------------------------ */

// 单条 WebSocket 配置。所有字段都是可选的，提供默认值兜底。
export type FCTypeWebSocketConfig = {
	// 服务端地址，必填。
	url : string
	// 心跳间隔（秒）。<= 0 表示不启用心跳。
	heartTime ?: number
	// 心跳消息内容，默认 'ping'。
	heartMessage ?: string
	// 心跳超时（秒），默认 = heartTime * 2。
	heartTimeoutTime ?: number
	// 最大重连次数。-1 表示无限重连，默认 5。
	maxReconnectAttempts ?: number
	// 首次重连延迟（毫秒），默认 3000。
	reconnectDelay ?: number
	// 最大重连延迟（毫秒），默认 30000。
	maxReconnectDelay ?: number
	// 指数退避倍数，默认 2。
	reconnectDelayMultiplier ?: number
	// 消息队列上限，超过后丢弃最早的消息并触发 onError，默认 100。
	messageQueueMaxSize ?: number
	// 请求拦截器，可在调用 uni.connectSocket 前调整 options。
	requestInterceptors ?: (config : ConnectSocketOptions) => void
	// onOpen / onMessage / onError / onClose 事件回调
	onOpen ?: (event : OnSocketOpenCallbackResult) => void
	onMessage ?: (data : string) => void
	onError ?: (error : GeneralCallbackResult) => void
	onClose ?: (event : any) => void
	// 重连尝试 / 成功 / 失败
	onReconnectAttempt ?: (attempt : number, delay : number) => void
	onReconnectSuccess ?: () => void
	onReconnectFailed ?: (totalAttempts : number) => void
}

/* ------------------------------------------------------------------ */
/* UniPush 2.0                                                         */
/* ------------------------------------------------------------------ */

export type FCTypeUniPushChannel = {
	channelId : string
	channelDesc : string
	soundName ?: string
	enableLights ?: boolean
	enableVibration ?: boolean
	importance ?: number
	lockscreenVisibility ?: number
}

export type FCTypeUniPushLocalMessage = {
	cover ?: boolean
	delay ?: number
	icon ?: string
	sound ?: string
	title ?: string
	channelId ?: string
	category ?: string
}

// 小米/红米角标通知的标题与内容。setBadgeNumber 时未显式传 options 会用它兜底。
export type FCTypeUniPushBadgeMessage = {
	title ?: string
	content ?: string
}

export type FCTypeUniPushConfig = {
	autoGetClientId ?: boolean
	autoListen ?: boolean
	requestPermission ?: boolean
	createLocalOnReceive ?: boolean
	channels ?: FCTypeUniPushChannel[]
	localMessage ?: FCTypeUniPushLocalMessage
	onClientId ?: (cid : string) => void
	onClientIdFail ?: (error : UniError) => void
	onReceive ?: (data : UTSJSONObject) => void
	onClick ?: (data : UTSJSONObject) => void
	onMessage ?: (res : OnPushMessageCallbackResult) => void
	onNeedNotificationPermission ?: () => void
	badgeMessage ?: FCTypeUniPushBadgeMessage
}
