// Code generated by fc-uniapp-x. DO NOT EDIT.
// 20261001

import fs from 'node:fs'
import path from 'node:path'
import type { Plugin } from 'vite'

type ThemeValues = Record<string, string>

type ThemeConfig = {
	light: ThemeValues
	dark: ThemeValues
}

const SYSTEM_THEME_KEYS = new Set([
	'navigationBarTextStyle',
	'backgroundTextStyle',
	'tabBarBorderStyle',
	'tabBarIconPath',
	'tabBarSelectedIconPath',
	'androidThreeButtonNavigationBackgroundColor',
])

const COLOR_RULES = [
	['bg', 'background-color'],
	['text', 'color'],
	['c', 'color'],
	['color', 'color'],
	['b', 'border-color'],
	['border', 'border-color'],
	['fill', 'fill'],
	['stroke', 'stroke'],
] as const

function toKebabCase(value: string) {
	return value
		.replace(/([a-z0-9])([A-Z])/g, '$1-$2')
		.replace(/_/g, '-')
		.toLowerCase()
}

function toCssVariables(values: ThemeValues, keys: string[]) {
	return keys
		.map((key) => `\t--fc-theme-${toKebabCase(key)}: ${values[key]};`)
		.join('\n')
}

function toRootThemeVariables(mode: string, values: ThemeValues, keys: string[]) {
	return `.${mode} {\n${keys
		.map((key) => `\t--fc-theme-${toKebabCase(key)}: ${values[key]};`)
		.join('\n')}\n}`
}

function readTheme(themePath: string) {
	const theme = JSON.parse(fs.readFileSync(themePath, 'utf8')) as ThemeConfig
	const lightKeys = Object.keys(theme.light)
	const darkKeys = Object.keys(theme.dark)

	if (lightKeys.length === 0 || darkKeys.length === 0) {
		throw new Error('theme.json 的 light 和 dark 均不能为空')
	}

	const missingInDark = lightKeys.filter((key) => !(key in theme.dark))
	const missingInLight = darkKeys.filter((key) => !(key in theme.light))
	if (missingInDark.length > 0 || missingInLight.length > 0) {
		throw new Error(
			`theme.json 的 light/dark Token 必须一致。dark 缺少: ${missingInDark.join(', ') || '无'}；light 缺少: ${missingInLight.join(', ') || '无'}`,
		)
	}

	return { theme, lightKeys }
}

export function createThemeUnoConfig(rootDir = process.cwd()) {
	const themePath = path.resolve(rootDir, 'theme.json')
	const pagesPath = path.resolve(rootDir, 'pages.json')
	const { lightKeys } = readTheme(themePath)
	const colorKeys = lightKeys.filter((key) => !SYSTEM_THEME_KEYS.has(key))
	const rules = colorKeys.flatMap((key) => {
		const token = toKebabCase(key)
		return COLOR_RULES.map(([prefix, property]) => [
			`fc-${prefix}-${token}`,
			{ [property]: `var(--fc-theme-${token})` },
		])
	})
	const pageFiles = new Set(
		Array.from(fs.readFileSync(pagesPath, 'utf8').matchAll(/"path"\s*:\s*"([^"]+)"/g))
			.flatMap((match) => [
				path.resolve(rootDir, `${match[1]}.uvue`),
				path.resolve(rootDir, `${match[1]}.vue`),
			]),
	)

	const createCss = () => {
		const currentTheme = readTheme(themePath).theme
		return `@media (prefers-color-scheme: light) {
page {
${toCssVariables(currentTheme.light, colorKeys)}
}
}

@media (prefers-color-scheme: dark) {
page {
${toCssVariables(currentTheme.dark, colorKeys)}
}
}

${toRootThemeVariables('fc-theme-light', currentTheme.light, colorKeys)}

${toRootThemeVariables('fc-theme-dark', currentTheme.dark, colorKeys)}`
	}

	const vitePlugin: Plugin = {
		name: 'theme-json-css-variables',
		enforce: 'pre',
		configureServer(devServer) {
			devServer.watcher.add(themePath)
		},
		handleHotUpdate(context) {
			if (path.resolve(context.file) !== themePath) return
			readTheme(themePath)
			context.server.restart()
			return []
		},
		transform(code: string, id: string) {
			if (id.includes('App.uvue')) {
				return {
					code: code.replace('</style>', `${createCss()}\n</style>`),
					map: null,
				}
			}
			if (!/\.(?:uvue|vue)(?:\?|$)/.test(id)) return null
			if (!/<template>\s*<[^>]+/.test(code)) return null
			const filePath = path.resolve(id.split('?')[0])
			const isPage = pageFiles.has(filePath)
			const setupCode = `import { FC as __FC } from '@/fcuni/index.ts'${isPage ? '\n\nonShow(() => {\n\t__FC.Theme.syncSystemTheme()\n})' : ''}`
			let injected = /<script setup([^>]*)>/.test(code)
				? code.replace(/<script setup([^>]*)>/, `<script setup$1>\n${setupCode}\n`)
				: `<script setup lang="uts">\n${setupCode}\n</script>\n${code}`
			injected = injected.replace(
				/(<template>\s*<[^>]+?)(>)/,
				(_match, openingTag: string, closing: string) => {
					const dynamicClass = /\s:class=(['"])(.*?)\1/.exec(openingTag)
					if (dynamicClass == null) {
					return `${openingTag} :class="'fc-theme-' + __FC.Theme.state.mode"${closing}`
					}
					return `${openingTag.replace(dynamicClass[0], ` :class="[${dynamicClass[2]}, 'fc-theme-' + __FC.Theme.state.mode]"`)}${closing}`
				},
			)
			return {
				code: injected,
				map: null,
			}
		},
	}

	return {
		rules,
		vitePlugin,
	}
}
