// Code generated by fc-uniapp-x. DO NOT EDIT.
// 20261001

import PAGES from "@/pages.json"
import type { FCTypeRouterConfig, FCTypeRouteParams } from '@/fcuni/types'

type PageItem = UTSJSONObject

type SubPackageItem = UTSJSONObject

const ROUTE_API_NAMES = ['navigateTo', 'redirectTo', 'switchTab', 'reLaunch']

class FCRouter {
	config : FCTypeRouterConfig = {}

	private routeInterceptor : AddInterceptorOptions | null = null

	private interceptDepth : number = 0

	private verifyMap : Record<string, boolean> = {}

	private buildUrl(path : string, params ?: FCTypeRouteParams) : string {
		const url = '/' + path
		const query = params != null ? FCRouter.serializeParams(params) : ''
		return url + query
	}

	static serializeParams(params : FCTypeRouteParams) : string {
		const keys = Object.keys(params)
		if (keys.length == 0) return ''

		const parts : string[] = []
		for (let i = 0; i < keys.length; i++) {
			const key = keys[i]
			const value = params[key]
			if (value == null) continue

			let encoded : string
			if (typeof value == 'object') {
				encoded = encodeURIComponent(JSON.stringify(value) ?? '') ?? ''
			} else {
				encoded = encodeURIComponent(String(value)) ?? ''
			}
			parts.push(key + '=' + encoded)
		}

		return parts.length == 0 ? '' : '?' + parts.join('&')
	}

	parseParams(params : FCTypeRouteParams) : string {
		return FCRouter.serializeParams(params)
	}

	parse<T>(value : any, fallback : T) : T {
		if (typeof value != 'string' || value.length == 0) return fallback
		try {
			const decoded = decodeURIComponent(value)
			if (decoded == null || decoded.length == 0) return fallback
			return JSON.parse(decoded) as T
		} catch (error) {
			console.error('路由参数解析失败', error)
			return fallback
		}
	}

	init(config ?: FCTypeRouterConfig) : this {
		if (config != null) {
			this.config = { ...config }
		}

		this.removeInterceptor()
		this.verifyMap = {}

		const pages = (PAGES as UTSJSONObject)['pages']
		if (Array.isArray(pages)) {
			this.collectPages(pages as PageItem[])
		}

		const subPackages = (PAGES as UTSJSONObject)['subPackages']
		if (Array.isArray(subPackages)) {
			const packageItems = subPackages as SubPackageItem[]
			for (let i = 0; i < packageItems.length; i++) {
				const packageItem = packageItems[i]
				const root = packageItem['root']
				const packagePages = packageItem['pages']
				if (typeof root != 'string' || !Array.isArray(packagePages)) continue
				this.collectPages(packagePages as PageItem[], root)
			}
		}

		this.routeInterceptor = this.createRouteInterceptor()
		for (let i = 0; i < ROUTE_API_NAMES.length; i++) {
			uni.addInterceptor(ROUTE_API_NAMES[i], this.routeInterceptor as AddInterceptorOptions)
		}

		return this
	}

	private collectPages(pages : PageItem[], root : string = '') : void {
		const normalizedRoot = this.normalizePath(root)
		for (let i = 0; i < pages.length; i++) {
			const page = pages[i]
			const path = page['path']
			if (typeof path != 'string') continue
			const fullPath = normalizedRoot.length > 0
				? normalizedRoot + '/' + this.normalizePath(path)
				: this.normalizePath(path)
			this.verifyMap[fullPath] = page['verify'] === true
		}
	}

	private normalizePath(path : string) : string {
		let result = path.split('?')[0]
		while (result.startsWith('/')) result = result.slice(1)
		while (result.endsWith('/')) result = result.slice(0, result.length - 1)
		return result
	}

	private shouldAllow(targetPath : string) : boolean {
		if (this.interceptDepth > 0) return true
		if (this.verifyMap[this.normalizePath(targetPath)] !== true) return true

		const guard = this.config.shouldInterceptRoute
		const shouldBlock = guard != null ? guard() : false
		if (!shouldBlock) return true

		const onBlocked = this.config.interceptFunc
		if (onBlocked != null) {
			this.interceptDepth++
			try {
				onBlocked()
			} finally {
				this.interceptDepth--
			}
		}
		return false
	}

	private createRouteInterceptor() : AddInterceptorOptions {
		return {
			invoke: (args : UTSJSONObject) : boolean => {
				const url = args['url']
				return typeof url != 'string' || this.shouldAllow(url)
			},
		} as AddInterceptorOptions
	}

	removeInterceptor() : void {
		if (this.routeInterceptor != null) {
			for (let i = 0; i < ROUTE_API_NAMES.length; i++) {
				uni.removeInterceptor(ROUTE_API_NAMES[i], this.routeInterceptor)
			}
			this.routeInterceptor = null
		}
	}

	go(path : string, params ?: FCTypeRouteParams) : void {
		uni.navigateTo({ url: this.buildUrl(path, params) })
	}
}

export const Router = new FCRouter()
