// Code generated by fc-uniapp-x. DO NOT EDIT.
// 20261001

type PersistPluginContext = {
	store : any,
	options : any,
}

type ResolvedOptions = {
	key : string,
	paths : string[] | null,
	debounceMs : number,
}

const DEFAULT_DEBOUNCE_MS = 100

function resolveOptions(context : PersistPluginContext) : ResolvedOptions | null {
	const options = context.options
	if (options == null) return null

	const persist = options['persist']
	if (persist == null) return null

	const keyValue = persist['key']
	if (typeof keyValue != 'string') return null

	const key = keyValue as string
	if (key.length == 0) return null

	const pathsValue = persist['paths']
	let paths : string[] | null = null
	if (Array.isArray(pathsValue)) {
		const filtered : string[] = []
		for (let i = 0; i < pathsValue.length; i++) {
			const item = pathsValue[i]
			if (typeof item == 'string' && (item as string).length > 0) {
				filtered.push(item as string)
			}
		}
		paths = filtered.length > 0 ? filtered : null
	}

	const debounceValue = persist['debounceMs']
	const debounceMs = typeof debounceValue == 'number' && (debounceValue as number) > 0
		? (debounceValue as number)
		: DEFAULT_DEBOUNCE_MS

	return { key, paths, debounceMs }
}

function readFromStorage(storageKey : string) : UTSJSONObject | null {
	let raw : any = null
	try {
		raw = uni.getStorageSync(storageKey)
	} catch (e) {
		console.warn('[fc-pinia][persist] read storage failed for ' + storageKey + ':', e)
		return null
	}

	if (typeof raw != 'string') return null
	const text = raw as string
	if (text.length == 0) return null

	try {
		const parsed = JSON.parse(text) as UTSJSONObject | null
		if (parsed == null) return null
		return parsed
	} catch (e) {
		console.warn('[fc-pinia][persist] parse stored payload failed for ' + storageKey + ':', e)
		return null
	}
}

function pickByPaths(state : any, paths : string[] | null) : UTSJSONObject {
	const result = {} as UTSJSONObject
	if (paths == null) {
		try {
			const raw = JSON.stringify(state)
			if (raw == null) return result
			const parsed = JSON.parse(raw) as UTSJSONObject | null
			if (parsed == null) return result
			return parsed
		} catch (e) {
			console.warn('[fc-pinia][persist] serialize state failed:', e)
			return result
		}
	}

	const src : any = state
	for (let i = 0; i < paths.length; i++) {
		const field = paths[i]
		if (src[field] === undefined) continue
		try {
			const fieldRaw = JSON.stringify(src[field])
			if (fieldRaw == null) continue
			const fieldParsed = JSON.parse(fieldRaw) as UTSJSONObject | null
			if (fieldParsed != null) {
				result[field] = fieldParsed
			}
		} catch (e) {
			console.warn('[fc-pinia][persist] serialize field "' + field + '" failed:', e)
		}
	}
	return result
}

function applyPickedData(store : any, data : UTSJSONObject, paths : string[] | null) : void {
	if (paths == null) {
		store.$patch(data)
		return
	}

	const patch = {} as UTSJSONObject
	for (let i = 0; i < paths.length; i++) {
		const field = paths[i]
		if (data[field] !== undefined) {
			patch[field] = data[field]
		}
	}
	store.$patch(patch)
}

function writeToStorage(storageKey : string, payload : UTSJSONObject) : void {
	try {
		const serialized = JSON.stringify(payload)
		if (serialized == null) return
		uni.setStorageSync(storageKey, serialized as string)
	} catch (e) {
		console.warn('[fc-pinia][persist] write storage failed for ' + storageKey + ':', e)
	}
}

function createDebouncer(delayMs : number, fn : () => void) : () => void {
	let timerId : number | null = null
	return () => {
		if (timerId != null) {
			clearTimeout(timerId as number)
		}
		timerId = setTimeout(() => {
			timerId = null
			fn()
		}, delayMs) as number
	}
}

export function createPersistPlugin() : (context : PersistPluginContext) => void {
	return (context : PersistPluginContext) : void => {
		const opts = resolveOptions(context)
		if (opts == null) return

		const store = context.store

		const cached = readFromStorage(opts.key)
		if (cached != null) {
			applyPickedData(store, cached, opts.paths)
		}

		store.$subscribe((_mutation : any, _state : any) : void => {
			try {
				const state = store.$state
				const picked = pickByPaths(state, opts.paths)

				if (UTSJSONObject.keys(picked).length == 0) {
					try {
						uni.removeStorageSync(opts.key)
					} catch (e) {
						console.warn('[fc-pinia][persist] remove empty storage failed for ' + opts.key + ':', e)
					}
					return
				}

				writeToStorage(opts.key, picked)
			} catch (e) {
				console.warn('[fc-pinia][persist] subscribe handler failed:', e)
			}
		}, { detached: true, flush: 'sync' })
	}
}

export function clearPersistedState(storageKey : string) : void {
	try {
		uni.removeStorageSync(storageKey)
	} catch (e) {
		console.warn('[fc-pinia][persist] clear failed for ' + storageKey + ':', e)
	}
}

export function hasPersistedState(storageKey : string) : boolean {
	try {
		const raw = uni.getStorageSync(storageKey)
		return typeof raw == 'string' && (raw as string).length > 0
	} catch (e) {
		return false
	}
}
